[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://track-connect-api-kd00.onrender.com/api"
  VITE_SOCKET_URL = "https://track-connect-api-kd00.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
